from datetime import datetime, timezone
from fastapi import APIRouter

from app.database import get_supabase
from app.models.logs import MedicationLogCreateRequest, SideEffectLogCreateRequest

router = APIRouter()


def _ensure_user_exists(user_id: str):
    db = get_supabase()
    try:
        db.table("users").upsert({"id": user_id}).execute()
    except Exception:
        pass


@router.post("/med-logs")
async def create_med_log(req: MedicationLogCreateRequest):
    _ensure_user_exists(req.user_id)
    db = get_supabase()
    row = {
        "user_id": req.user_id,
        "medication_id": req.medication_id,
        "date": req.date.isoformat(),
        "scheduled_time": req.scheduled_time,
        "taken": req.taken,
        "taken_at": datetime.now(timezone.utc).isoformat() if req.taken else None,
    }
    # id is UUID auto-generated by Supabase
    result = db.table("med_logs").insert(row).execute()
    log_id = result.data[0]["id"] if result.data else None
    return {"status": "logged", "id": log_id}


@router.post("/side-effects/log")
async def create_side_effect_log(req: SideEffectLogCreateRequest):
    _ensure_user_exists(req.user_id)
    db = get_supabase()
    row = {
        "user_id": req.user_id,
        "effect": req.effect,
        "severity": req.severity,
        "date": req.date.isoformat(),
        "notes": req.notes,
    }
    # id is UUID auto-generated by Supabase
    result = db.table("side_effect_logs").insert(row).execute()
    log_id = result.data[0]["id"] if result.data else None
    return {"status": "logged", "id": log_id}
